#build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /app

COPY . .

RUN dotnet restore CEP.SmartWallet.Api/CEP.SmartWallet.Api.csproj
RUN dotnet publish CEP.SmartWallet.Api/CEP.SmartWallet.Api.csproj -c Release -o /app/out

#runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app

COPY --from=build /app/out .

ENTRYPOINT [ "dotnet", "CEP.SmartWallet.Api.dll" ]