apiVersion: v1
kind: Service
metadata:
  name: cep-smartwallet-api
  namespace: cep-smartwallet
spec:
  selector:
    app: cep-smartwallet-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30009
  type: NodePort
